// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCo4Cg1DcmVhdHVyZVN0YXRlEggKBElk",
            "bGUQABIICgRNb3ZlEAESCQoFU2tpbGwQAhIICgREZWFkEAMqOgoHTW92ZURp",
            "chIICgROb25lEAASBgoCVXAQARIICgREb3duEAISCAoETGVmdBADEgkKBVJp",
            "Z2h0EAQqIgoJRXJyb3JUeXBlEgsKB1N1Y2Nlc3MQABIICgRGYWlsEAFCF6oC",
            "FEdvb2dsZS5Qcm90b2J1Zi5FbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.CreatureState), typeof(global::Google.Protobuf.Enum.MoveDir), typeof(global::Google.Protobuf.Enum.ErrorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CreatureState {
    [pbr::OriginalName("Idle")] Idle = 0,
    [pbr::OriginalName("Move")] Move = 1,
    [pbr::OriginalName("Skill")] Skill = 2,
    [pbr::OriginalName("Dead")] Dead = 3,
  }

  public enum MoveDir {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Up")] Up = 1,
    [pbr::OriginalName("Down")] Down = 2,
    [pbr::OriginalName("Left")] Left = 3,
    [pbr::OriginalName("Right")] Right = 4,
  }

  public enum ErrorType {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Fail")] Fail = 1,
  }

  #endregion

}

#endregion Designer generated code
