// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCo4Cg1DcmVhdHVyZVN0YXRlEggKBElk",
            "bGUQABIICgRNb3ZlEAESCQoFU2tpbGwQAhIICgREZWFkEAMqMAoHTW92ZURp",
            "chIGCgJVcBAAEggKBERvd24QARIICgRMZWZ0EAISCQoFUmlnaHQQAypDCg5H",
            "YW1lT2JqZWN0VHlwZRIICgROb25lEAASCgoGUGxheWVyEAESCwoHTW9uc3Rl",
            "chACEg4KClByb2plY3RpbGUQBCpBCglTa2lsbFR5cGUSDgoKU2tpbGxfTm9u",
            "ZRAAEg4KClNraWxsX0F1dG8QARIUChBTa2lsbF9Qcm9qZWN0aWxlEAIqXAoR",
            "UGxheWVyU2VydmVyU3RhdGUSFgoSU2VydmVyX1N0YXRlX0xvZ2luEAASFgoS",
            "U2VydmVyX1N0YXRlX0xvYmJ5EAESFwoTU2VydmVyX1N0YXRlX0luR2FtZRAC",
            "KmsKCUVycm9yVHlwZRILCgdTdWNjZXNzEAASCAoERmFpbBABEhgKFEludmFs",
            "aWRfU2VydmVyX1N0YXRlEAoSFgoSQWxyZWFkeV9FeGlzdF9OYW1lEBQSFQoR",
            "SW52YWxpZF9HYW1lX0RhdGEQHkIXqgIUR29vZ2xlLlByb3RvYnVmLkVudW1i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.CreatureState), typeof(global::Google.Protobuf.Enum.MoveDir), typeof(global::Google.Protobuf.Enum.GameObjectType), typeof(global::Google.Protobuf.Enum.SkillType), typeof(global::Google.Protobuf.Enum.PlayerServerState), typeof(global::Google.Protobuf.Enum.ErrorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CreatureState {
    [pbr::OriginalName("Idle")] Idle = 0,
    [pbr::OriginalName("Move")] Move = 1,
    [pbr::OriginalName("Skill")] Skill = 2,
    [pbr::OriginalName("Dead")] Dead = 3,
  }

  public enum MoveDir {
    [pbr::OriginalName("Up")] Up = 0,
    [pbr::OriginalName("Down")] Down = 1,
    [pbr::OriginalName("Left")] Left = 2,
    [pbr::OriginalName("Right")] Right = 3,
  }

  public enum GameObjectType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Player")] Player = 1,
    [pbr::OriginalName("Monster")] Monster = 2,
    [pbr::OriginalName("Projectile")] Projectile = 4,
  }

  public enum SkillType {
    [pbr::OriginalName("Skill_None")] SkillNone = 0,
    [pbr::OriginalName("Skill_Auto")] SkillAuto = 1,
    [pbr::OriginalName("Skill_Projectile")] SkillProjectile = 2,
  }

  public enum PlayerServerState {
    [pbr::OriginalName("Server_State_Login")] ServerStateLogin = 0,
    [pbr::OriginalName("Server_State_Lobby")] ServerStateLobby = 1,
    [pbr::OriginalName("Server_State_InGame")] ServerStateInGame = 2,
  }

  public enum ErrorType {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Fail")] Fail = 1,
    [pbr::OriginalName("Invalid_Server_State")] InvalidServerState = 10,
    [pbr::OriginalName("Already_Exist_Name")] AlreadyExistName = 20,
    [pbr::OriginalName("Invalid_Game_Data")] InvalidGameData = 30,
  }

  #endregion

}

#endregion Designer generated code
