// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqVAQoFTXNnSWQSCAoETm9uZRAAEhoK",
            "FlMyQ19CUk9BRENBU1RFTlRFUkdBTUUQARIRCg1DMlNfTEVBVkVHQU1FEAIS",
            "GgoWUzJDX0JST0FEQ0FTVExFQVZFR0FNRRADEhIKDlMyQ19QTEFZRVJMSVNU",
            "EAQSDAoIQzJTX01PVkUQBRIVChFTMkNfQlJPQURDQVNUTU9WRRAGKiIKCUVy",
            "cm9yVHlwZRILCgdTdWNjZXNzEAASCAoERmFpbBABQheqAhRHb29nbGUuUHJv",
            "dG9idWYuRW51bWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.MsgId), typeof(global::Google.Protobuf.Enum.ErrorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("S2C_BROADCASTENTERGAME")] S2CBroadcastentergame = 1,
    [pbr::OriginalName("C2S_LEAVEGAME")] C2SLeavegame = 2,
    [pbr::OriginalName("S2C_BROADCASTLEAVEGAME")] S2CBroadcastleavegame = 3,
    [pbr::OriginalName("S2C_PLAYERLIST")] S2CPlayerlist = 4,
    [pbr::OriginalName("C2S_MOVE")] C2SMove = 5,
    [pbr::OriginalName("S2C_BROADCASTMOVE")] S2CBroadcastmove = 6,
  }

  public enum ErrorType {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Fail")] Fail = 1,
  }

  #endregion

}

#endregion Designer generated code
